/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#1d2027",
        "on-surface-variant": "#c2c6d6",
        "primary-fixed-dim": "#adc6ff",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "outline": "#8c909f",
        "surface-container-low": "#191b23",
        "tertiary-container": "#8691a7",
        "inverse-on-surface": "#2e3038",
        "error-container": "#93000a",
        "on-secondary-container": "#adb4ce",
        "surface-container-lowest": "#0b0e15",
        "on-surface": "#e1e2ec",
        "secondary": "#bec6e0",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-background": "#e1e2ec",
        "surface-container-highest": "#32353c",
        "primary-container": "#4d8eff",
        "on-primary-container": "#00285d",
        "surface-bright": "#363941",
        "outline-variant": "#424754",
        "on-primary-fixed": "#001a42",
        "primary": "#adc6ff",
        "on-primary": "#002e6a",
        "tertiary": "#bcc7de",
        "surface-tint": "#adc6ff",
        "surface-variant": "#32353c",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "background": "#10131a",
        "surface-container-high": "#272a31",
        "on-secondary": "#283044",
        "surface-dim": "#10131a",
        "inverse-surface": "#e1e2ec",
        "tertiary-fixed-dim": "#bcc7de",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-primary": "#005ac2",
        "secondary-container": "#3f465c",
        "on-tertiary-fixed": "#111c2d",
        "tertiary-fixed": "#d8e3fb",
        "on-error": "#690005",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-container": "#1f2a3c",
        "on-primary-fixed-variant": "#004395",
        "surface": "#10131a",
        "secondary-fixed": "#dae2fd",
        "on-tertiary": "#263143",
        // Legacy aliases
        accent: '#f59e0b',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        headline: ['Inter'],
        data: ['JetBrains Mono'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
      },
      animation: {
        'scan': 'scan 3s ease-in-out infinite',
      },
      keyframes: {
        scan: {
          '0%': { top: '0', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { top: '100%', opacity: '0' },
        },
      },
    },
  },
  plugins: [],
}
